name: Build and push Docker image to GHCR on push

on:
  push:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ryphier/wizarr

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH.PAT }}
        run: |
          docker login --username ryphier --password ${{ secrets.GH.PAT }} ghcr.io
          docker build . --tag ghcr.io/ryphier/wizarr:latest
          docker push . ghcr.io/ryphier/wizarr:latest

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images : ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags : dev # use a fixed tag 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses : docker/build-push-action@v2 
        with :
          platforms : linux/amd64,linux/arm64,linux/arm/v7 # specify architectures here 
          context : .
          file : ./Dockerfile
          push : true # set this to false if you don't want to push 
          tags : ${{ steps.meta.outputs.tags }} # use metadata action output 
          labels : ${{ steps.meta.outputs.labels }} # use metadata action output 
